# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 620)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 605))
        MainWindow.setMaximumSize(QtCore.QSize(600, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.page = QtWidgets.QTabWidget(self.centralwidget)
        self.page.setGeometry(QtCore.QRect(250, 10, 341, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page.sizePolicy().hasHeightForWidth())
        self.page.setSizePolicy(sizePolicy)
        self.page.setAutoFillBackground(True)
        self.page.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.page.setIconSize(QtCore.QSize(40, 40))
        self.page.setObjectName("page")
        self.explore = QtWidgets.QWidget()
        self.explore.setObjectName("explore")
        self.groupBox_2 = QtWidgets.QGroupBox(self.explore)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 311, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 291, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.yuhun_single = QtWidgets.QRadioButton(self.layoutWidget)
        self.yuhun_single.setObjectName("yuhun_single")
        self.gridLayout.addWidget(self.yuhun_single, 0, 0, 1, 1)
        self.yuhun_driver = QtWidgets.QRadioButton(self.layoutWidget)
        self.yuhun_driver.setObjectName("yuhun_driver")
        self.gridLayout.addWidget(self.yuhun_driver, 0, 1, 1, 1)
        self.yuhun_passenger = QtWidgets.QRadioButton(self.layoutWidget)
        self.yuhun_passenger.setObjectName("yuhun_passenger")
        self.gridLayout.addWidget(self.yuhun_passenger, 0, 2, 1, 1)
        self.yuhun_two = QtWidgets.QRadioButton(self.layoutWidget)
        self.yuhun_two.setChecked(True)
        self.yuhun_two.setObjectName("yuhun_two")
        self.gridLayout.addWidget(self.yuhun_two, 1, 0, 1, 1)
        self.yuhun_three = QtWidgets.QRadioButton(self.layoutWidget)
        self.yuhun_three.setObjectName("yuhun_three")
        self.gridLayout.addWidget(self.yuhun_three, 1, 1, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.explore)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 180, 311, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 310, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.need_mark_shi_shen = QtWidgets.QCheckBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.need_mark_shi_shen.sizePolicy().hasHeightForWidth())
        self.need_mark_shi_shen.setSizePolicy(sizePolicy)
        self.need_mark_shi_shen.setObjectName("need_mark_shi_shen")
        self.horizontalLayout_2.addWidget(self.need_mark_shi_shen)
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.mark_shi_shen_pos_index = QtWidgets.QSpinBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mark_shi_shen_pos_index.sizePolicy().hasHeightForWidth())
        self.mark_shi_shen_pos_index.setSizePolicy(sizePolicy)
        self.mark_shi_shen_pos_index.setMinimum(1)
        self.mark_shi_shen_pos_index.setMaximum(5)
        self.mark_shi_shen_pos_index.setObjectName("mark_shi_shen_pos_index")
        self.horizontalLayout_2.addWidget(self.mark_shi_shen_pos_index)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.explore)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 280, 311, 251))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 291, 221))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border: none;")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.page.addTab(self.explore, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 311, 131))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 291, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.yuhun_single_2 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.yuhun_single_2.setObjectName("yuhun_single_2")
        self.gridLayout_2.addWidget(self.yuhun_single_2, 0, 0, 1, 1)
        self.yuhun_driver_2 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.yuhun_driver_2.setObjectName("yuhun_driver_2")
        self.gridLayout_2.addWidget(self.yuhun_driver_2, 0, 1, 1, 1)
        self.yuhun_passenger_2 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.yuhun_passenger_2.setObjectName("yuhun_passenger_2")
        self.gridLayout_2.addWidget(self.yuhun_passenger_2, 0, 2, 1, 1)
        self.yuhun_two_2 = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.yuhun_two_2.setChecked(True)
        self.yuhun_two_2.setObjectName("yuhun_two_2")
        self.gridLayout_2.addWidget(self.yuhun_two_2, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 240, 311, 291))
        self.groupBox_6.setObjectName("groupBox_6")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 20, 291, 261))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("border: none;")
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 150, 311, 81))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 291, 26))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.n_ka_slider = QtWidgets.QSlider(self.layoutWidget_3)
        self.n_ka_slider.setProperty("value", 20)
        self.n_ka_slider.setOrientation(QtCore.Qt.Horizontal)
        self.n_ka_slider.setObjectName("n_ka_slider")
        self.horizontalLayout_3.addWidget(self.n_ka_slider)
        self.page.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.page.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_2.setGeometry(QtCore.QRect(5, 1, 321, 451))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.textEdit_2.setFont(font)
        self.textEdit_2.setAutoFillBackground(False)
        self.textEdit_2.setStyleSheet("border: none;")
        self.textEdit_2.setLineWidth(0)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 460, 311, 71))
        self.groupBox_9.setObjectName("groupBox_9")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_9)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 30, 291, 30))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.page.addTab(self.tab_4, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 201, 61))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 280, 241, 331))
        self.groupBox.setObjectName("groupBox")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(5, 21, 231, 301))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(8)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("border=none;")
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(250, 580, 341, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_btn = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_btn.sizePolicy().hasHeightForWidth())
        self.start_btn.setSizePolicy(sizePolicy)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout.addWidget(self.start_btn)
        self.end_btn = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_btn.sizePolicy().hasHeightForWidth())
        self.end_btn.setSizePolicy(sizePolicy)
        self.end_btn.setObjectName("end_btn")
        self.horizontalLayout.addWidget(self.end_btn)
        self.quit_btn = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_btn.sizePolicy().hasHeightForWidth())
        self.quit_btn.setSizePolicy(sizePolicy)
        self.quit_btn.setObjectName("quit_btn")
        self.horizontalLayout.addWidget(self.quit_btn)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 200, 231, 71))
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 30, 216, 23))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.system_resize_resolution = QtWidgets.QComboBox(self.layoutWidget3)
        self.system_resize_resolution.setMaxVisibleItems(2)
        self.system_resize_resolution.setObjectName("system_resize_resolution")
        self.system_resize_resolution.addItem("")
        self.system_resize_resolution.addItem("")
        self.gridLayout_3.addWidget(self.system_resize_resolution, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.page.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "阴阳师辅助脚本"))
        self.groupBox_2.setTitle(_translate("MainWindow", "模式"))
        self.yuhun_single.setText(_translate("MainWindow", "单刷"))
        self.yuhun_driver.setText(_translate("MainWindow", "司机"))
        self.yuhun_passenger.setText(_translate("MainWindow", "乘客"))
        self.yuhun_two.setText(_translate("MainWindow", "双开"))
        self.yuhun_three.setText(_translate("MainWindow", "三开"))
        self.groupBox_3.setTitle(_translate("MainWindow", "参数"))
        self.need_mark_shi_shen.setText(_translate("MainWindow", "自动标记式神"))
        self.label_2.setText(_translate("MainWindow", "从左往右位置:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "注意事项"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:11.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1.进入房间后邀请队友，选好对应的模式和参数，锁定阵容后点击开始按钮.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2.游戏窗体可以被遮挡，但是不能最小化.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3.式神标记功能只针对司机有效，乘客无法标记.</span></p></body></html>"))
        self.page.setTabText(self.page.indexOf(self.explore), _translate("MainWindow", "御魂副本"))
        self.groupBox_5.setTitle(_translate("MainWindow", "模式"))
        self.yuhun_single_2.setText(_translate("MainWindow", "单刷"))
        self.yuhun_driver_2.setText(_translate("MainWindow", "司机"))
        self.yuhun_passenger_2.setText(_translate("MainWindow", "乘客"))
        self.yuhun_two_2.setText(_translate("MainWindow", "双开"))
        self.groupBox_6.setTitle(_translate("MainWindow", "注意事项"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:11.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1.</span><span style=\" font-size:9pt; font-weight:600; color:#ff007f;\">双开模式,司机模式</span><span style=\" font-size:9pt;\">先邀请队友刷一次，退出后出现\'是否继续邀请队友\'按钮时点击开始脚本.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2.</span><span style=\" font-size:9pt; font-weight:600; color:#ff007f;\">乘客模式</span><span style=\" font-size:9pt;\">开启脚本等待司机邀请即可.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">3.仅刷经验怪和boss.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">4.式神目录里取消式神折叠功能，用滑动块控制换上的1级N卡位置，不能对N卡设置喜欢.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">5.不要点锁定阵容，不然无法更换狗粮</span></p></body></html>"))
        self.groupBox_7.setTitle(_translate("MainWindow", "参数"))
        self.label_3.setText(_translate("MainWindow", "1级N卡的大概位置："))
        self.page.setTabText(self.page.indexOf(self.tab_2), _translate("MainWindow", "探索"))
        self.page.setTabText(self.page.indexOf(self.tab), _translate("MainWindow", "百鬼夜行"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:11.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">1.1111111</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">2.2222222</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">3.3333333</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">4.4444444</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">5.5555555</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">6.6666666</span></p></body></html>"))
        self.groupBox_9.setTitle(_translate("MainWindow", "激活代码"))
        self.pushButton.setText(_translate("MainWindow", "保存"))
        self.page.setTabText(self.page.indexOf(self.tab_4), _translate("MainWindow", "关于"))
        self.label.setText(_translate("MainWindow", "阴阳师辅助脚本"))
        self.groupBox.setTitle(_translate("MainWindow", "日志"))
        self.start_btn.setText(_translate("MainWindow", "开始"))
        self.end_btn.setText(_translate("MainWindow", "停止"))
        self.quit_btn.setText(_translate("MainWindow", "退出"))
        self.groupBox_8.setTitle(_translate("MainWindow", "全局参数"))
        self.label_7.setText(_translate("MainWindow", "WIN10系统缩放比例："))
        self.system_resize_resolution.setItemText(0, _translate("MainWindow", "125%"))
        self.system_resize_resolution.setItemText(1, _translate("MainWindow", "100%"))
